name: TDisableCrafts
main: minealex.tdisablecrafts.TDisableCrafts
version: 1.0
api-version: 1.8

commands:
  tdc:
    description: Reload the DisableCrafts config
    usage: /<command>
    permission: tdc.reload
